name = "reverse-proxy-ywca"
main = "src/worker.js"
workers_dev = false
compatibility_date = "2025-10-03"
account_id = "7b2f784c5831c5cb430bad3d4eb6d0a3"

[observability]
enabled = true
head_sampling_rate = 1

# Development environment
[env.development]
name = "reverse-proxy-ywca-dev"
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
name = "reverse-proxy-ywca-staging"
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
name = "reverse-proxy-ywca-production"
vars = { ENVIRONMENT = "production" }

[[env.production.routes]]
pattern = "ywcaofmissoula.com/*"
zone_name = "ywcaofmissoula.com"
