name = "reverse-proxy-ywca"
main = "src/worker.js"
workers_dev = false
compatibility_date = "2025-10-03"
account_id = "e6537b26b3f9444de8e670aa4442fd6e"

[observability]
enabled = true
head_sampling_rate = 1

# Routes - shared across all environments
[[routes]]
pattern = "ywcaofmissoula.com/*"
zone_name = "ywcaofmissoula.com"

# Development environment
[env.development]
vars = { ENVIRONMENT = "development" }

# Staging environment
[env.staging]
vars = { ENVIRONMENT = "staging" }

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }
