name = "reverse-proxy-ywca-production"
main = "src/worker.js"
workers_dev = false
compatibility_date = "2025-10-03"
account_id = "e6537b26b3f9444de8e670aa4442fd6e"

# Environment variables
[vars]
ENVIRONMENT = "production"
ANALYTICS_TOKEN = "d42a1351b9ef4539894a367233dc068e"

[observability]
enabled = true
head_sampling_rate = 1

# Routes
[[routes]]
pattern = "ywcaofmissoula.com/*"
zone_name = "ywcaofmissoula.com"

# Note: This worker is pre-configured for production
# Environment configs removed to prevent name duplication (reverse-proxy-ywca-production-production)
# Deploy with: wrangler deploy (no --env flag needed)
