name = "sitemap-ywcaofmissoula-com"
main = "src/worker.js"
workers_dev = true
preview_urls = true
compatibility_date = "2025-10-03"

[[routes]]
pattern = "*ywcaofmissoula.com/sitemap.xml"
zone_name = "ywcaofmissoula.com"

[observability]
enabled = true
head_sampling_rate = 1
