name = "dynamic-robots-generator"
main = "src/worker.js"
workers_dev = true
preview_urls = true
compatibility_date = "2025-10-03"

# Route for root domain
[[routes]]
pattern = "ywcaofmissoula.com/robots.txt"
zone_name = "ywcaofmissoula.com"

# Route for www subdomain
[[routes]]
pattern = "www.ywcaofmissoula.com/robots.txt"
zone_name = "ywcaofmissoula.com"

[observability]
enabled = true
head_sampling_rate = 1
