# dynamic-robots-generator-ywcaofmissoula-com/wrangler.toml
name = 'dynamic-robots-generator-ywcaofmissoula-com'
main = "src/worker.ts"
compatibility_date = "2024-12-18"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
ENVIRONMENT = "production"
CACHE_TTL = "3600"
RATE_LIMIT_REQUESTS = "100"
RATE_LIMIT_WINDOW = "60000"
ANALYTICS_ENABLED = "true"

# KV namespace bindings
[[kv_namespaces]]
binding = "ROBOTS_CACHE"
id = "994035050fab47688db9d3a164e4ba47"

# Routes will be added after deployment
# [[routes]]
# pattern = "ywcaofmissoula.com/robots.txt"
# zone_name = "ywcaofmissoula.com"

# [[routes]]
# pattern = "www.ywcaofmissoula.com/robots.txt"
# zone_name = "ywcaofmissoula.com"

# Development environment
[env.dev]
vars = { ENVIRONMENT = "development", CACHE_TTL = "300", ANALYTICS_ENABLED = "false" }

# Staging environment
[env.staging]
vars = { ENVIRONMENT = "staging", CACHE_TTL = "1800", ANALYTICS_ENABLED = "true" }

# Production environment
[env.production]
vars = { ENVIRONMENT = "production", CACHE_TTL = "3600", ANALYTICS_ENABLED = "true" }

# Observability and monitoring
[observability]
enabled = true
head_sampling_rate = 1

# Performance and limits
[limits]
cpu_ms = 50

# TypeScript is handled automatically by Wrangler
